services:
  mini-container:
    build: .
    healthcheck:
      test: ["CMD", "./build/0.1.0/mini-docker", "-m", "/mnt/mini-docker"]
      interval: 5s
      retries: 1
    volumes:
      - .:/root/mini-docker
    cap_add: 
      - SYS_ADMIN
    privileged: true
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    cgroup: host
